/* Proprietà intellettuale di Francesco Antonio Binetti */
// Generated by scripts/build-agenda-index.js
// Do not edit by hand.
globalThis.AGENDA_INDEX = {
  "hs01-componenti.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Le parti dell'hardware · Il ciclo che ogni computer ripete, poi processore, RAM, dischi, scheda madre e alimentatore.",
      "02 Collegamenti e connessioni · Input e output, porte e cavi, USB, e le reti senza fili: WiFi, Bluetooth e dati mobili.",
      "03 Il software · I programmi che non si toccano: il sistema operativo, il browser e la suite per ufficio."
    ]
  },
  "hs02-hard-disk-filesystem.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Dove finiscono i dati · RAM contro spazio disco, HDD e SSD, e le unità di misura da bit a terabyte.",
      "02 Il file system · Partizioni e percorsi, metadati e permessi, e i formati FAT32, exFAT, NTFS, ext4, APFS.",
      "03 Gestire i file · Organizzare le cartelle, la salute del disco, la compressione (ZIP, 7z, RAR) e i link."
    ]
  },
  "hs03-os.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Usare il sistema · Leggere lo schermo, aprire e chiudere le attività, e cosa gestisce l'OS sotto.",
      "02 I sistemi operativi · Windows, macOS, Linux e Android, e libero contro open source contro proprietario.",
      "03 Come si differenziano · App, sicurezza e aggiornamenti, raccolta dati e personalizzazione a confronto."
    ]
  },
  "hs04-os-concetti.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 App, sistema e installazione · App contro documento contro account, le versioni e cosa succede davvero installando.",
      "02 Sotto il cofano · I driver come ponte con l'hardware, gli aggiornamenti, le licenze e gli store digitali.",
      "03 Sicurezza e manutenzione · Utenti e privilegi, backup e ripristino, e come riconoscere il proprio sistema."
    ]
  },
  "hs05-troubleshooting.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Il metodo · Dove sta il problema, la checklist dei primi 60 secondi, capire prima di agire e isolare le variabili.",
      "02 Problemi comuni · Browser, schermo bloccato, rete, app che crasha, stampante, lentezza, disco pieno e codici d'errore.",
      "03 Chiedere aiuto e prevenire · FAQ, forum e community, come chiedere aiuto nel modo giusto, e imparare per prevenire."
    ]
  },
  "rw01-01-reti.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Cos'è una rete · Le tipologie di rete e come i dispositivi si connettono tra loro.",
      "02 Internet e il Web · Cos'è Internet, perché non coincide col World Wide Web, e come viaggia una richiesta.",
      "03 Client, server e rischi · Chi chiede e chi risponde, i vantaggi delle reti e i loro rischi."
    ]
  },
  "rw01-02-navigazione.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Navigare e i protocolli · Cosa significa navigare, i protocolli di rete e HTTP contro HTTPS.",
      "02 L'indirizzo web · Cos'è un URL e la sua anatomia, pezzo per pezzo.",
      "03 Domini e link · Cos'è un dominio e cos'è un collegamento ipertestuale."
    ]
  },
  "rw01-03-domini.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Anatomia di un dominio · Le parti di un dominio, quelli geografici e quelli tematici.",
      "02 DNS e registrazione · Il DNS che traduce gli indirizzi, come si registra un dominio e i sottodomini.",
      "03 Leggere un URL · Riconoscere un indirizzo sospetto, con pratica guidata."
    ]
  },
  "rw01-04-ricerca.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Link e navigazione · Cosa sono i collegamenti, come riconoscerli, i tipi e la loro sicurezza.",
      "02 Cercare informazioni · Motori di ricerca, parole chiave, operatori avanzati e leggere una SERP.",
      "03 Strumenti online · Moduli, enciclopedie, dizionari e la traduzione automatica coi suoi limiti."
    ]
  },
  "rw01-05-affidabilita.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Valutare l'affidabilità · Perché farlo, i rischi, riconoscere un sito sicuro e perché HTTPS non basta.",
      "02 Chi, cosa, quando · Lo scopo del sito, l'autore, le fonti, la data e il pubblico di riferimento.",
      "03 Navigare sicuri · Acquisti online, dati personali, logout, controllo parentale e monitoraggio."
    ]
  },
  "rw02-01-email.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 L'email e l'indirizzo · Cos'è la posta elettronica, l'indirizzo e le piattaforme principali.",
      "02 Scrivere un'email · Destinatari, CC e CCN, oggetto, corpo, tono e allegati.",
      "03 Buone pratiche · Rispondere, riconoscere email sospette, sicurezza, netiquette e ordine."
    ]
  },
  "rw02-02-firma.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Perché una firma · Cos'è una firma email, a cosa serve e le informazioni essenziali.",
      "02 Cosa mettere · Nome, ruolo, azienda, recapiti, sito e profili social.",
      "03 Formato e pratica · La formattazione, un esempio, gli errori comuni, i disclaimer e la firma automatica."
    ]
  },
  "rw02-03-contenuti.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Visualizzare e salvare · Cosa sono i contenuti digitali, i formati, salvare pagine, segnalibri, stampa e PDF.",
      "02 Copiare e scaricare · Scaricare file, copiare testo e immagini, multimedia, screenshot e OCR.",
      "03 Cloud e diritti · Il cloud, organizzare l'archivio, il copyright e le Creative Commons."
    ]
  },
  "rw02-04-collaborazione-digitale.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 La tua presenza online · L'impronta digitale, curare il profilo e la netiquette che ti rappresenta.",
      "02 Comunicare · Email professionale, canali sincroni e asincroni, messaggistica e fusi orari.",
      "03 Collaborare · Documenti condivisi, strumenti di project management e kanban, riunioni e videochiamate."
    ]
  },
  "rw02-05-account-email.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Creare l'account · La procedura passo per passo, e come farlo anche senza numero di telefono.",
      "02 Proteggerlo · L'email di riserva per il recupero e dove custodire le credenziali.",
      "03 Tenerlo pulito · Archiviare, filtrare, disiscriversi e la manutenzione periodica."
    ]
  },
  "rw03-01-identita.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Identità e strumenti · Privata contro professionale, e SPID e PEC per dimostrare chi sei online.",
      "02 Dati e livelli · Dati personali e categorie particolari, i tre livelli di SPID, PEC contro email.",
      "03 Farsi trovare bene · La prima impressione, l'impronta digitale e comunicare bene con i clienti."
    ]
  },
  "rw03-02-societa.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Tecnologia e benessere · L'effetto sull'umore, inclusione contro isolamento e l'uso incontrollato.",
      "02 Progettare per tutti · La progettazione con empatia, l'accessibilità e i sistemi che si adattano.",
      "03 Lavoro e società · Lo smart working, proteggere i dati da casa e la digitalizzazione."
    ]
  },
  "rw03-03-vr-ar.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Realtà virtuale · Cos'è l'immersione, come funziona un sistema VR e dove si usa.",
      "02 Realtà aumentata · Il digitale sovrapposto al reale, i suoi componenti e gli usi quotidiani.",
      "03 Il metaverso · VR contro AR, cosa definisce un metaverso e dove esiste oggi."
    ]
  },
  "rw03-04-branding.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Cos'è la brand identity · Identity contro image, di cosa è fatta, vision e mission.",
      "02 Conoscere il pubblico · Il target di pubblico e come profilare i clienti.",
      "03 La voce del brand · Logo, palette, font e un tono coerente su ogni canale."
    ]
  },
  "rw03-05-social.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Scegliere i social · I passi della promozione, i social più usati e quale scegliere per chi.",
      "02 Creare contenuti · Pianificare in anticipo, contenuti che funzionano, insights e gestione dei commenti.",
      "03 Crescere · La pubblicità di base, il blog per farsi trovare e cosa non pubblicare."
    ]
  },
  "cd01-01-licenze-oer.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Diritto d'autore e licenze · Diritti morali e patrimoniali, la paternità dell'opera e cosa significa una licenza.",
      "02 Creative Commons · Le licenze CC, da BY a NC, la CC0 e attribuire col metodo TASL.",
      "03 Remix e OER · Adattamento e compatibilità, le risorse educative aperte e le 5R."
    ]
  },
  "cd01-02-accessibilita-immagini.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Perché l'accessibilità · Accessibile significa percepibile, e il requisito WCAG 1.1.1.",
      "02 Che funzione ha l'immagine · Informativa, funzionale o decorativa, e l'attributo alt giusto per ciascuna.",
      "03 Casi difficili · Quando alt vuoto non basta, le immagini complesse e l'albero decisionale."
    ]
  },
  "cd01-03-metadati-formati.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 I metadati · Cosa sono, perché servono in archivio e le tre famiglie utili.",
      "02 Qualità e privacy · Indicizzare bene, la qualità dei metadati e quelli sensibili.",
      "03 I formati immagine · Raster e vettoriale, JPEG, PNG, SVG e quale formato scegliere."
    ]
  },
  "cd01-04-sicurezza-contenuti.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Superficie d'attacco · Account, archivi e piattaforme come sistema collegato.",
      "02 Controllo e provenienza · DRM, watermark, registri, hash e metadati.",
      "03 CMS resilienti · Plugin, permessi minimi, manutenzione, backup e risposta agli incidenti."
    ]
  },
  "cd02-01-podcast-storytelling.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Il racconto · Il nucleo narrativo, pubblico e promessa, struttura lineare e non lineare.",
      "02 Scrivere e registrare · Scrivere per l'ascolto, la scaletta di un podcast e il livello in registrazione.",
      "03 Montaggio e audio · Il montaggio editoriale, picco contro loudness e la normalizzazione."
    ]
  },
  "sm01-smartphone-computer.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Dentro lo smartphone · La scheda logica, CPU, SoC e RAM, la memoria interna e la batteria.",
      "02 Schermo e sensori · Il touch, le fotocamere, il GPS, i sensori di movimento, microfoni e altoparlanti.",
      "03 Un computer particolare · Il confronto con altri dispositivi e i suoi limiti fisici."
    ]
  },
  "sm02-connessioni-reti-mobili.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Reti senza fili · WiFi, WiFi pubblico e VPN, Bluetooth e NFC.",
      "02 Rete cellulare · Da 2G a 5G, SIM ed eSIM, hotspot, giga e roaming.",
      "03 Posizione e problemi · Modalità aereo, localizzazione assistita e quando Internet non va."
    ]
  },
  "sm03-android-ios.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 I due sistemi · Il sistema operativo mobile, Android e iOS a confronto.",
      "02 Account e store · Account Google e Apple ID, gli store ufficiali e il sideloading.",
      "03 Ecosistemi e backup · Aggiornamenti di sistema e app, i due ecosistemi, backup e quale scegliere."
    ]
  },
  "sm04-app-permessi.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Le app · Cosa sono, gli store ufficiali e come riconoscere quelle pericolose.",
      "02 I permessi · Fotocamera e microfono, posizione, contatti e file, e come controllarli e revocarli.",
      "03 Gestire le app · Notifiche, background e aggiornamenti, rimuoverle e gli abbonamenti."
    ]
  },
  "sm05-privacy-telefono.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Cosa raccoglie · Cosa raccoglie il telefono, il tracciamento pubblicitario e la posizione.",
      "02 Dati e contenuti · Foto e metadati, cloud e backup, rubrica, messaggi, browser e social.",
      "03 Proteggersi · Permessi periodici, condivisione involontaria, privacy dei minori e checklist."
    ]
  },
  "sm06-sicurezza-smartphone.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Chiudere a chiave · Il telefono come chiave, blocco schermo e biometria, 2FA e codici OTP.",
      "02 Furto e truffe · Prepararsi al furto, telefono rubato, SIM swap, smishing e vishing.",
      "03 Difese quotidiane · Malware e fonti dubbie, aggiornamenti, WiFi pubbliche e la checklist."
    ]
  },
  "sm07-file-telefono.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 I file sul telefono · File anche qui, l'app File, download e documenti.",
      "02 Dove stanno · Foto e allegati, cloud e backup, spazio e cache.",
      "03 Spostare e proteggere · Trasferire al PC, la condivisione, i file sensibili e i nomi chiari."
    ]
  },
  "sm08-fotocamera-contenuti.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 I file che produci · Risoluzione e peso, compressione e formati, la fotocamera computazionale.",
      "02 Creare e modificare · Editing, scanner e QR code, screenshot e registrazione, e scattare bene.",
      "03 Gestire e condividere · Galleria e backup, i metadati EXIF, la condivisione consapevole e il diritto d'immagine."
    ]
  },
  "sm09-benessere-digitale.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Uso consapevole · Il tempo sullo schermo, le notifiche e l'autoplay.",
      "02 Ritagliare pause · Non disturbare e focus, notte e sonno.",
      "03 Attenzione ai rischi · Dipendenza e social, la messaggistica, bambini e adolescenti, e i segnali."
    ]
  },
  "sm10-accessibilita-uso-pratico.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Vedere meglio · Testo e contrasto, dark mode, zoom e lente.",
      "02 Voce e udito · La lettura dello schermo, voce e dettatura, e se l'udito non aiuta.",
      "03 Uso pratico · Modalità semplificata, autonomia quotidiana, emergenze e traduzione."
    ]
  },
  "sm11-manutenzione-scelta.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Far durare il telefono · Aggiornamenti e supporto, memoria e RAM, la batteria e la ricarica, la protezione fisica.",
      "02 Riparare o cambiare · Il diritto alla riparazione, riparare o sostituire, nuovo o ricondizionato, e la checklist.",
      "03 Fine vita · Preparare il telefono alla vendita, l'impatto ambientale e lo smaltimento RAEE."
    ]
  },
  "su01-01-microsoft.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Le app principali · Word, Excel, PowerPoint, Outlook, Teams e OneDrive.",
      "02 Il resto della suite · Le altre app di Microsoft 365 e cosa offrono.",
      "03 Scegliere e proteggere · Abbonamento o licenza, Microsoft contro alternative e la sicurezza aziendale."
    ]
  },
  "su01-02-google-workspace.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Account e Drive · Cos'è la suite Google, l'account e Drive, e cosa significa davvero condividere.",
      "02 Le app di lavoro · Docs, Sheets, Slides, Gmail, Calendar, Meet, Forms e Classroom.",
      "03 Flusso e strumenti · Il flusso di lavoro tipico, i file Google/Office/PDF, le buone abitudini e le lavagne."
    ]
  },
  "su01-03-adobe.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Creative Cloud · Cos'è, e la differenza tra grafica raster e vettoriale.",
      "02 Le app principali · Photoshop, Illustrator, InDesign, Premiere Pro e Acrobat.",
      "03 Scegliere · Quale app per quale lavoro, e il resto di Creative Cloud."
    ]
  },
  "su01-04-alternativi.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Cos'è l'open source · Il concetto e le principali licenze open source.",
      "02 Gli strumenti · LibreOffice, GIMP, Inkscape, DaVinci Resolve e altri consigliati.",
      "03 Scegliere · Commerciale contro alternativo."
    ]
  },
  "su02-01-documenti.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Documenti di lavoro · Tre documenti chiave e la scheda cliente.",
      "02 Il curriculum · Cosa contiene, l'ordine giusto, esperienze, titoli e competenze.",
      "03 Listini e privacy · Privacy e più curriculum, e i listini e le promo."
    ]
  },
  "su02-02-word-scrivere-formattare.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Basi del documento · L'interfaccia, creare, aprire e salvare, e selezionare senza fatica.",
      "02 Formattare il testo · Gerarchia tipografica, paragrafi e spaziatura, elenchi e trova e sostituisci.",
      "03 Gli stili · La vera scorciatoia, applicata al listino del modulo precedente."
    ]
  },
  "su02-03-word-impaginare-revisionare.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Impaginare · La pagina, intestazioni e numeri, interruzioni e sezioni.",
      "02 Elementi e revisione · Tabelle, immagini e didascalie, commenti e menzioni.",
      "03 Rifinire · Revisioni e confronto, controllo finale ed esportazione."
    ]
  },
  "su02-04-word-documenti-professionali.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Partire bene · Dal brief ai modelli e all'identità visiva.",
      "02 Documenti tipo · Lettera ed email formale, report, moduli compilabili e stampa unione.",
      "03 Documenti lunghi · Sommario, versioni e metadati, fino al kit professionale riutilizzabile."
    ]
  },
  "su03-01-sistema.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Il foglio di calcolo · Cos'è, le parti dell'interfaccia e i tipi di dati in una cella.",
      "02 Lavorare coi dati · Inserire e modificare, più fogli in un file, e rendere i dati leggibili.",
      "03 Produrre · Creare un grafico, preparare la stampa e condividere il file."
    ]
  },
  "su03-02-riferimenti.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 L'indirizzo delle celle · Riferimenti relativi, assoluti col simbolo dollaro, e misti.",
      "02 Range e nomi · I range, nominare celle e range, e i riferimenti a colonne e altri fogli.",
      "03 Formule solide · La funzione LET e cosa rompe le formule, e come evitarlo."
    ]
  },
  "su03-03-fondamenti-matematici.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Gli insiemi · Insiemi numerici, operazioni, diagrammi di Venn e le loro leggi fondamentali.",
      "02 La logica · Proposizioni e tabelle di verità, quantificatori, De Morgan e la logica nei fogli.",
      "03 Le funzioni · Dominio e grafico, i tipi di funzione, e composizione e funzione inversa."
    ]
  },
  "su03-04-prime-formule.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Come funziona una formula · Gli operatori aritmetici e logici, e la funzione più usata.",
      "02 Contare · Contare le celle presenti, con una condizione, e le decisioni automatiche.",
      "03 Buone abitudini · Le otto funzioni del modulo, gli errori tipici e le buone abitudini."
    ]
  },
  "su03-05-analisi.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Ordinare e riassumere · Tabelle strutturate, ordinamento e filtri, tabelle pivot e FILTER.",
      "02 Cercare · Ricerca verticale e orizzontale, trovare la posizione ed estrarre per posizione.",
      "03 La ricerca giusta · INDICE+CONFRONTA, CERCA.X e quale funzione di ricerca scegliere."
    ]
  },
  "su03-06-funzioni-top.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Somma e conteggio condizionali · SOMMA.PIÙ.SE, CONTA.PIÙ.SE e la media che sceglie.",
      "02 Numeri puliti · Totali che seguono i filtri, gestire gli errori, arrotondare e formattare.",
      "03 Date e riepilogo · OGGI, ADESSO e DATA, e le nove funzioni del modulo."
    ]
  },
  "su03-07-testo.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Dati sporchi · Da tante celle a una, SPLIT, e TROVA e RICERCA per posizione.",
      "02 Correggere · SOSTITUISCI e RIMPIAZZA, gli spazi invisibili e i numeri travestiti da testo.",
      "03 La cassetta degli attrezzi · MAIUSC, MINUSC e MAIUSC.INIZ, la pulizia in catena e le funzioni testo."
    ]
  },
  "su03-08-tabelle-pivot.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Perché una pivot · Quando la tabella è troppo lunga e la regola una riga uguale un record.",
      "02 Costruirla · Da tabella a pivot, righe, colonne, valori e filtri, e somma, conteggio, media.",
      "03 Usarla bene · Vedere solo ciò che serve, aggiornare la pivot e sapere quando mente."
    ]
  },
  "su03-09-tabelle-pivot-avanzate.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 La domanda giusta · La domanda viene prima dei campi, e lo stesso valore raccontato in più modi.",
      "02 Analisi avanzata · Percentuali, confronti tra periodi, raggruppare date e campi calcolati.",
      "03 Cruscotti · Segmentazioni e timeline, il grafico pivot, più pivot su una sorgente e i controlli."
    ]
  },
  "su03-10-grafici.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Scegliere il grafico · Il grafico come risposta visiva: barre, linee, composizione, dispersione e istogramma.",
      "02 Grafici avanzati · Combinati, secondo asse, area, cascata, radar, heatmap e sparkline.",
      "03 Leggere e sintetizzare · Trendline, media mobile, previsione, annotazioni e la dashboard finale."
    ]
  },
  "su03-11-fogli-calcolo-avanzati.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Dati puliti · Non solo una griglia, una tabella pulita, i tipi di dato e impedire gli errori.",
      "02 Controllo e struttura · Formattazione condizionale, intervalli nominati e importazione CSV.",
      "03 Cloud e consegna · Proteggere le celle, lavorare in cloud, dal foglio al cruscotto e la checklist."
    ]
  },
  "su03-12-query-fogli-calcolo.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Cos'è una query · SELECT, WHERE e ORDER BY, e la funzione QUERY in Google Sheets.",
      "02 Filtrare e raggruppare · Le colonne utili, le condizioni, ordinare, GROUP BY e PIVOT.",
      "03 Oltre Sheets · Power Query in Excel, unire tabelle e la query come pipeline di pulizia."
    ]
  },
  "su03-13-macro-fogli-calcolo.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Cos'è una macro · Automatizzare solo processi stabili e registrare una macro.",
      "02 Rendere utile la macro · Riferimenti relativi o assoluti, la sicurezza, i pulsanti e i parametri.",
      "03 Macro affidabili · Gestire gli errori, testare su copie, i limiti e la checklist."
    ]
  },
  "su03-14-vba.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Fondamenti · L'editor e i moduli, Sub e Function, variabili e tipi, e Option Explicit.",
      "02 Costrutti · Range e Cells, With, condizioni, Select Case e i cicli.",
      "03 In produzione · Errori, performance, file, eventi, UserForm, sicurezza e progetto finale."
    ]
  },
  "su03-15-google-apps-script.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Fondamenti · Cos'è Apps Script, l'editor, JavaScript essenziale e SpreadsheetApp.",
      "02 Automazione · getValues e setValues, menu, trigger, autorizzazioni e i servizi Gmail, Drive e UrlFetch.",
      "03 In produzione · JSON, HTML Service e web app, proprietà e lock, debug, quote e deployment."
    ]
  },
  "su03-16-segmentazioni.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Cosa sono gli slicer · Filtri a pulsante che si aggiungono e si leggono con un clic, in Excel e in Google Sheets.",
      "02 Filtri interattivi · La timeline temporale e collegare un solo controllo a più tabelle e grafici.",
      "03 Progettare i controlli · Scegliere i filtri che contano davvero ed evitare cruscotti confusi."
    ]
  },
  "su03-17-collegamenti-fogli.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Riferimenti tra schede · Richiamare una cella di un'altra scheda dello stesso file di calcolo.",
      "02 Collegare file diversi · IMPORTRANGE per tirare dati da un altro foglio di calcolo, e le autorizzazioni.",
      "03 Tenere i collegamenti sani · Filtrare i dati importati, aggiornamenti e permessi, e non spezzare le catene."
    ]
  },
  "su03-18-oltre-il-foglio.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Quando il foglio non basta · I segnali che hai superato il limite dello strumento.",
      "02 Farsi costruire il software · Descrivere il problema all'IA, iterare e verificare: le formule diventano regole.",
      "03 Rischi e criterio · Codice non capito, manutenzione, dati — e quando il foglio resta la scelta giusta."
    ]
  },
  "su04-01-presentazioni.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Progettare · Cos'è PowerPoint, saper presentare, e la struttura inizio, corpo e fine.",
      "02 Slide efficaci · Un'idea per slide, meno testo, colori e font, immagini e animazioni.",
      "03 Consegnare · Le slide non bastano, provare fa la differenza, gli errori comuni e i post social."
    ]
  },
  "sd01-introduzione.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Cos'è la sicurezza digitale · La triade CID, cosa dobbiamo proteggere e quanto vale la nostra impronta digitale.",
      "02 Perché riguarda tutti · Non solo le grandi aziende né solo gli esperti: la superficie d'attacco e il fattore umano.",
      "03 Le difese di base · Aggiornamenti, password, autenticazione a due fattori, crittografia e buone abitudini."
    ]
  },
  "sd02-minacce.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Le minacce · Minacce contro vulnerabilità, il malware, ransomware, phishing e ingegneria sociale.",
      "02 Gli attacchi · Reti WiFi, man-in-the-middle, botnet e DDoS, zero-day e doxing.",
      "03 Difendersi · Antivirus ed EDR, backup, mettere in sicurezza la rete, VPN e cosa fare se attaccati."
    ]
  },
  "sd03-privacy.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Privacy e tracciamento · Cos'è la privacy, i diritti del GDPR, come veniamo tracciati e i metadati.",
      "02 Anonimato e strumenti · Anonimato e pseudonimato, TOR, browser e ricerca rispettosi della privacy.",
      "03 Proteggere la privacy · Social, telefono, diritto all'oblio, messaggi privati e la checklist finale."
    ]
  },
  "sd04-professioni.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 I ruoli · Analyst e SOC, penetration tester, incident responder, engineer, architect e CISO.",
      "02 Le reti che servono · Cos'è Internet, i dispositivi, come viaggiano i dati e i protocolli DNS e HTTPS.",
      "03 Entrare nel settore · I percorsi di formazione e la mappa delle professioni."
    ]
  },
  "sd05-assessment.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Vulnerability assessment · Le cinque fasi, il punteggio CVSS e la differenza col penetration test.",
      "02 Compliance e normative · Le principali normative, le regole, le responsabilità e le licenze.",
      "03 I tuoi dati · Quali dati abbiamo e dove sono, chi li raccoglie e perché, e come riprenderne il controllo."
    ]
  },
  "sd06-piani-b-digitali.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Il principio · Ogni anello può cedere: la catena deve reggere lo stesso. Trovare i punti deboli.",
      "02 Le reti di sicurezza · Email di riserva, codici di recupero, backup 3-2-1, copie dei documenti.",
      "03 Gli scenari · Perdo il telefono, l'email, il PC: per ognuno, la contromossa già pronta."
    ]
  },
  "ia01-concetti-generali.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Cos'è l'IA · Cos'è, la storia, i concetti correlati, le reti neurali e come impara una macchina.",
      "02 L'IA intorno a noi · Auto autonome, filter bubble e fake news, computer vision, deepfake e ChatGPT.",
      "03 Usarla con senso critico · Riconoscere gli elaborati IA, i bias, l'etica, la creatività, la privacy e il futuro."
    ]
  },
  "ia02-esercizio-generazione.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Gli strumenti · Per testo e conversazione, per audio e voce, per contenuti visivi.",
      "02 Il metodo · La metodologia dell'esercizio e come si crea qualcosa con l'IA.",
      "03 Scrivere prompt · Richieste chiare, prompt per testi e prompt per immagini."
    ]
  },
  "ia03-llm.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Cos'è un LLM · La definizione, cosa sono NLP e reti neurali profonde, e riconoscere un testo generato.",
      "02 Come comprende · Se comprende davvero, come «impara» il linguaggio umano e perché verificare l'output.",
      "03 Come funziona · La tokenizzazione, le reti di nodi, come interpreta il prompt e cosa non fa."
    ]
  },
  "ia04-diversi-modelli-ia.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Le famiglie · Modelli predittivi, generativi, multimodali e componenti specializzati.",
      "02 Gli ecosistemi · OpenAI, Google, Anthropic, Meta, Mistral AI e DeepSeek come esempi attuali.",
      "03 La scelta · Apertura, distribuzione, dimensione, costo, privacy e valutazione sul compito reale."
    ]
  },
  "pr01-01-introduzione-programmazione.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Cosa significa programmare · Esprimere un comportamento in un linguaggio, scritto perché lo capiscano due lettori: la macchina e le persone.",
      "02 I concetti di ogni linguaggio · Variabili e tipi, espressioni, controllo del flusso e procedure: i mattoni che ritrovi in qualunque linguaggio.",
      "03 Correttezza e limiti · Validità e famiglie di linguaggi, errori e test, e ciò che nessun programma può calcolare."
    ]
  },
  "pr01-02-dati-codifica.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Bit, byte e binario · Perché zero e uno, le unità della memoria, dal decimale al binario e la scrittura esadecimale.",
      "02 Codificare i contenuti · Testo, immagini e suono: come numeri e tabelle rappresentano ciò che vediamo e sentiamo.",
      "03 Formati e limiti · La compressione, i formati di file, il limite pratico dei numeri e l'ordine dei byte."
    ]
  },
  "pr01-03-algoritmi.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Cosa è un algoritmo · Una sequenza di passi controllabile, con le sue azioni fondamentali e i valori che conserva.",
      "02 Diagrammi di flusso · I simboli standard per disegnare il flusso e le regole per tenerlo leggibile.",
      "03 Progettare un algoritmo · Dai quattro passaggi al top-down, dallo pseudocodice a Flowgorithm, con pre e post-condizioni."
    ]
  },
  "pr01-04-costrutti-verifica.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Decisioni e cicli · Condizioni verificabili, le tre forme di ciclo, cicli annidati e uscite anticipate.",
      "02 Accumulatore e contatore · Costruire un risultato passo dopo passo, e sapere quante volte accade qualcosa.",
      "03 Verificare e valutare · La tabella di traccia, il costo di una soluzione e due esercizi da far girare."
    ]
  },
  "pr01-05-operatori-funzioni.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Operatori aritmetici · Somma, divisione, resto, potenza e assegnazione, con la precedenza che decide l'ordine dei calcoli.",
      "02 Confronto e logica · Confrontare valori, e combinare condizioni vere o false con AND, OR e NOT.",
      "03 Funzioni · Isolare una responsabilità in un blocco riusabile, capirne lo scope e verificarlo con esempi."
    ]
  },
  "pr01-06-python-base.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 La sintassi di Python · Simboli e indentazione: la forma che il codice deve avere per essere eseguito.",
      "02 Dati e input/output · Tipi e conversioni, liste, leggere ciò che entra e mostrare ciò che esce.",
      "03 Scrivere e correggere · Dallo pseudocodice al programma: le famiglie di errori, il debug e i commenti."
    ]
  },
  "pr01-07-iterazione-cicli.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Che cos'è un ciclo · Dalla ripetizione al ciclo, le sue parti e il ciclo condizionale.",
      "02 Scrivere e tracciare · Lo pseudocodice di un while, tracciare lo stato e il rischio del loop infinito.",
      "03 Costruire risultati · Accumulatore e contatore, e progettare un ciclo che si ferma."
    ]
  },
  "pr02-01-introduzione.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 L'ambiente Scratch · Online o offline, la mappa dell'interfaccia e come si leggono i blocchi.",
      "02 Muovere e far reagire · Movimento, eventi, sprite e stage, ripetizioni, decisioni e messaggi tra oggetti.",
      "03 Un progetto completo · Da Abby e il Gatto ai costumi, ai suoni, agli errori tipici e al salvataggio."
    ]
  },
  "pr02-02-questionario.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Impostare il quiz · I materiali, un file ordinato, le variabili e l'inizializzazione.",
      "02 Domande e logica · Porre domande, confronti case-sensitive, if/then/else, più risposte e punteggio.",
      "03 Struttura avanzata · Timer, architettura a messaggi, più sprite, liste e collaudo finale."
    ]
  },
  "pr03-01-microbit.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 La scheda · Il microcontrollore, il tour di fronte e retro e i sensori a bordo.",
      "02 L'ambiente MakeCode · Le aree dell'IDE, il simulatore e come si carica il codice sulla scheda.",
      "03 Programmare la scheda · Dai LED agli eventi fisici, le variabili, i progetti e il debug."
    ]
  },
  "pr03-02-createai.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 L'ambiente CreateAI · Avviare una sessione, le aree dell'IDE e la pipeline del progetto.",
      "02 Costruire il dataset · Azioni come etichette, registrare campioni, la qualità dei dati e allenare il modello.",
      "03 Usare il modello · Testarlo, correggerlo quando sbaglia, portarlo in MakeCode e documentarlo."
    ]
  },
  "pr04-01-editor-codice.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Conoscere l'editor · Perché gli strumenti differiscono, la cartella-progetto, VS Code e le estensioni.",
      "02 Eseguire e correggere · Il terminale, il debugger, e i tre controlli automatici: formatter, linter e test.",
      "03 Git · Registrare le modifiche, cosa non versionare, i conflitti e come si legge una diff."
    ]
  },
  "pr04-02-strumenti-ambiente.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Muoversi e modificare · Saltare alla definizione, rinominare senza rompere, cercare nel progetto e gli snippet.",
      "02 Scegliere lo strumento · IDE completi, altri editor, locale o nel browser, gli assistenti IA e quale scegliere.",
      "03 Preparare l'ambiente · Dipendenze e «sul mio computer funziona», i caratteri invisibili, l'ergonomia e il primo setup."
    ]
  },
  "pm01-introduzione.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Cos'è un progetto · Da un'idea a un risultato, progetto contro processo, il triplo vincolo e perché falliscono.",
      "02 Il ciclo di vita · Avvio, pianificazione, esecuzione, monitoraggio e chiusura.",
      "03 Il project manager · Le sue responsabilità, cosa non è, gli stakeholder e le soft skill."
    ]
  },
  "pm02-pianificazione.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Obiettivi e perimetro · Dal «che bello sarebbe» al piano, gli obiettivi SMART e cosa sta dentro o fuori.",
      "02 Attività e tempi · La WBS, le dipendenze, le stime, il diagramma di Gantt e le milestone.",
      "03 Budget, rischi, comunicazione · Chi fa cosa, il budget, i rischi con probabilità e impatto, e il piano di comunicazione."
    ]
  },
  "pm03-metodologie.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Predittivo o adattivo · Waterfall e la curva del costo del cambiamento, contro l'approccio agile a cicli.",
      "02 Scrum e Kanban · Dentro un'iterazione, gli sprint, il backlog e le user story, e visualizzare il flusso.",
      "03 Scegliere · Scrum o Kanban, quale metodo per quale progetto, gli approcci ibridi e le trappole."
    ]
  },
  "pm04-strumenti.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Perché uno strumento · Oltre il foglio di calcolo: le quattro famiglie di strumenti e le bacheche digitali.",
      "02 Cosa offrono · Automazioni, il Gantt che si aggiorna, la baseline, la dashboard, il burndown e il carico.",
      "03 Sceglierlo e introdurlo · Come si sceglie, come introdurlo senza rigetto e i quattro fallimenti da strumento."
    ]
  },
  "ms01-tinkercad-introduzione.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Cos'è TinkerCAD · Tre laboratori in uno e il progetto che vive nel cloud.",
      "02 Organizzarsi · Dashboard e progetti, le classi virtuali, la modalità sicura e la condivisione responsabile.",
      "03 Il primo oggetto · Dall'idea all'oggetto, costruendo una targhetta semplice."
    ]
  },
  "ms02-modellazione-base.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 L'ambiente · La mappa dell'ambiente, il piano di lavoro, la griglia di snap e il mouse come strumento.",
      "02 Costruire e modificare · Forme semplici, modificarle, i colori RGB, solidi e vuoti, raggruppare e separare.",
      "03 Muovere nello spazio · Spostare sugli assi, ruotare senza perdersi, e il mini-esercizio del portachiavi."
    ]
  },
  "ms03-esportazione-stampa-3d.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 I formati · Portare modelli dentro e fuori: SVG vettoriale, STL a triangoli, OBJ e come scegliere.",
      "02 Preparare la stampa · Da modello a istruzioni macchina, le forme che tradiscono la stampante e le tolleranze.",
      "03 Verificare e stampare · Simulare materiali e gravità, fino a una targhetta stampabile."
    ]
  },
  "ms04-classi-attivita.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 La classe · Crearla, gestirla e il progetto di partenza.",
      "02 Le attività · Un'attività passo-passo, adatta a ogni livello, e gli errori comuni in aula.",
      "03 Valutare · Badge, valutazione e i quattro criteri."
    ]
  },
  "ia05-strumenti-gratuiti.html": {
    "title": "Cosa vedremo",
    "items": [
      "01 Cosa vuol dire gratis · Freemium, dati come prezzo, e le categorie di strumenti disponibili.",
      "02 Gli strumenti · Chat, scrittura, immagini, audio, presentazioni, codice e ricerca.",
      "03 I limiti · Cosa perde la versione gratuita e come valutare uno strumento prima di usarlo."
    ]
  }
};
