/* Proprietà intellettuale di Francesco Antonio Binetti */
// Generated by scripts/build-exercise-index.js
// Do not edit by hand.
globalThis.EXERCISE_INDEX = {
  "cd01-01-licenze-oer.html": [
    {
      "file": "esercizi-contenuti-digitali.html",
      "slide": 2,
      "title": "Verifica: scegli e motiva"
    }
  ],
  "cd01-02-accessibilita-immagini.html": [
    {
      "file": "esercizi-contenuti-digitali.html",
      "slide": 3,
      "title": "Verifica: decorativa o informativa?"
    }
  ],
  "cd01-03-metadati-formati.html": [
    {
      "file": "esercizi-contenuti-digitali.html",
      "slide": 4,
      "title": "Verifica: archivio e logo"
    }
  ],
  "cd02-01-podcast-storytelling.html": [
    {
      "file": "esercizi-contenuti-digitali.html",
      "slide": 5,
      "title": "Verifica: racconta e consegna"
    }
  ],
  "ia02-esercizio-generazione.html": [
    {
      "file": "esercizi-intelligenza-artificiale.html",
      "slide": 2,
      "title": "Esercizio 1: l'inventario dell'ortofrutta"
    },
    {
      "file": "esercizi-intelligenza-artificiale.html",
      "slide": 3,
      "title": "Esercizio 2: il supermercato, con un'altra IA"
    },
    {
      "file": "esercizi-intelligenza-artificiale.html",
      "slide": 4,
      "title": "Esercizio 3: integrare i due inventari"
    }
  ],
  "ia04-diversi-modelli-ia.html": [
    {
      "file": "esercizi-intelligenza-artificiale.html",
      "slide": 5,
      "title": "Esercizio 4: riconoscere il modello giusto"
    }
  ],
  "ms02-modellazione-base.html": [
    {
      "file": "esercizi-modellazione-3d.html",
      "slide": 2,
      "title": "Mini-esercizio: il portachiavi"
    }
  ],
  "pr01-04-costrutti-verifica.html": [
    {
      "file": "esercizi-programmare.html",
      "slide": 2,
      "title": "Esercizio: tre diagrammi da far girare"
    },
    {
      "file": "esercizi-programmare.html",
      "slide": 3,
      "title": "Esercizio: tre diagrammi con un ciclo"
    }
  ],
  "pr01-07-iterazione-cicli.html": [
    {
      "file": "esercizi-programmare.html",
      "slide": 4,
      "title": "Verifica: progetta il ciclo"
    }
  ],
  "pr02-02-questionario.html": [
    {
      "file": "esercizi-programmare.html",
      "slide": 5,
      "title": "Collaudare il quiz"
    }
  ],
  "pr04-02-strumenti-ambiente.html": [
    {
      "file": "esercizi-programmare.html",
      "slide": 6,
      "title": "Esercizio: esplora senza installare tutto"
    }
  ],
  "rw02-01-email.html": [
    {
      "file": "esercizi-reti-web.html",
      "slide": 2,
      "title": "Esercitazione pratica"
    }
  ],
  "rw02-02-firma.html": [
    {
      "file": "esercizi-reti-web.html",
      "slide": 3,
      "title": "Laboratorio pratico"
    }
  ],
  "sd06-piani-b-digitali.html": [
    {
      "file": "esercizi-sicurezza.html",
      "slide": 2,
      "title": "Esercizio: mappa i tuoi punti unici"
    }
  ],
  "su03-03-fondamenti-matematici.html": [
    {
      "file": "esercizi-suite-ufficio.html",
      "slide": 2,
      "title": "Laboratorio: riconoscere struttura e funzione"
    }
  ],
  "su03-09-tabelle-pivot-avanzate.html": [
    {
      "file": "esercizi-suite-ufficio.html",
      "slide": 3,
      "title": "Laboratorio: cruscotto vendite"
    }
  ],
  "su03-10-grafici.html": [
    {
      "file": "esercizi-suite-ufficio.html",
      "slide": 4,
      "title": "Laboratorio: quattro domande, quattro grafici"
    },
    {
      "file": "su03-10-grafici.html",
      "slide": 27,
      "title": "Revisione finale: ricostruire un grafico debole"
    }
  ],
  "su03-16-segmentazioni.html": [
    {
      "file": "esercizi-suite-ufficio.html",
      "slide": 5,
      "title": "Esercizio: un cruscotto filtrabile"
    }
  ],
  "su03-17-collegamenti-fogli.html": [
    {
      "file": "esercizi-suite-ufficio.html",
      "slide": 6,
      "title": "Esercizio: sorgente e report"
    }
  ],
  "su03-18-oltre-il-foglio.html": [
    {
      "file": "esercizi-suite-ufficio.html",
      "slide": 7,
      "title": "Esercizio: dal foglio alla specifica"
    }
  ],
  "sm09-benessere-digitale.html": [
    {
      "file": "sm09-benessere-digitale.html",
      "slide": 3,
      "title": "Tempo sullo schermo"
    }
  ],
  "su03-14-vba.html": [
    {
      "file": "su03-14-vba.html",
      "slide": 2,
      "title": "Introduzione a VBA"
    },
    {
      "file": "su03-14-vba.html",
      "slide": 7,
      "title": "Range e Cells"
    },
    {
      "file": "su03-14-vba.html",
      "slide": 12,
      "title": "For Each"
    },
    {
      "file": "su03-14-vba.html",
      "slide": 17,
      "title": "Gestione errori"
    },
    {
      "file": "su03-14-vba.html",
      "slide": 22,
      "title": "Sicurezza e distribuzione"
    }
  ],
  "su03-15-google-apps-script.html": [
    {
      "file": "su03-15-google-apps-script.html",
      "slide": 2,
      "title": "Che cos’è Apps Script"
    },
    {
      "file": "su03-15-google-apps-script.html",
      "slide": 8,
      "title": "Range e fogli"
    },
    {
      "file": "su03-15-google-apps-script.html",
      "slide": 13,
      "title": "GmailApp"
    },
    {
      "file": "su03-15-google-apps-script.html",
      "slide": 18,
      "title": "Web app"
    },
    {
      "file": "su03-15-google-apps-script.html",
      "slide": 23,
      "title": "Deployment e versioni"
    }
  ],
  "pr02-01-introduzione.html": [
    {
      "file": "pr02-01-introduzione.html",
      "slide": 10,
      "title": "Progetto guidato: Abby e il Gatto"
    }
  ]
};
