/* Proprietà intellettuale di Francesco Antonio Binetti */
// Generated by scripts/build-exercise-index.js
// Do not edit by hand.
globalThis.EXERCISE_INDEX = {
  "decks/cd01-01-licenze-oer.html": [
    {
      "file": "decks/esercizi-contenuti-digitali.html",
      "slide": 2,
      "title": "Verifica: scegli e motiva"
    }
  ],
  "decks/cd01-02-accessibilita-immagini.html": [
    {
      "file": "decks/esercizi-contenuti-digitali.html",
      "slide": 3,
      "title": "Verifica: decorativa o informativa?"
    }
  ],
  "decks/cd01-03-metadati-formati.html": [
    {
      "file": "decks/esercizi-contenuti-digitali.html",
      "slide": 4,
      "title": "Verifica: archivio e logo"
    }
  ],
  "decks/cd02-01-podcast-storytelling.html": [
    {
      "file": "decks/esercizi-contenuti-digitali.html",
      "slide": 5,
      "title": "Verifica: racconta e consegna"
    }
  ],
  "decks/gd01-introduzione.html": [
    {
      "file": "decks/esercizi-game-design.html",
      "slide": 2,
      "title": "Analizza un gioco con MDA"
    }
  ],
  "decks/gd02-ost.html": [
    {
      "file": "decks/esercizi-game-design.html",
      "slide": 3,
      "title": "Analizza una OST"
    }
  ],
  "decks/gd03-sfx-audio.html": [
    {
      "file": "decks/esercizi-game-design.html",
      "slide": 4,
      "title": "Progetta il suono di un'azione"
    }
  ],
  "decks/gd04-feedback-sensoriale.html": [
    {
      "file": "decks/esercizi-game-design.html",
      "slide": 5,
      "title": "Che giocatore sei ?"
    }
  ],
  "decks/gd05-difficolta.html": [
    {
      "file": "decks/esercizi-game-design.html",
      "slide": 6,
      "title": "Analizza la curva"
    }
  ],
  "decks/gd06-meccaniche.html": [
    {
      "file": "decks/esercizi-game-design.html",
      "slide": 7,
      "title": "Smonta le meccaniche"
    }
  ],
  "decks/gd07-processo.html": [
    {
      "file": "decks/esercizi-game-design.html",
      "slide": 8,
      "title": "Valida un' idea"
    }
  ],
  "decks/gd08-progettazione.html": [
    {
      "file": "decks/esercizi-game-design.html",
      "slide": 9,
      "title": "Progetta le tue carte"
    }
  ],
  "decks/ia02-esercizio-generazione.html": [
    {
      "file": "decks/esercizi-intelligenza-artificiale.html",
      "slide": 2,
      "title": "Esercizio 1: l'inventario dell'ortofrutta"
    },
    {
      "file": "decks/esercizi-intelligenza-artificiale.html",
      "slide": 3,
      "title": "Esercizio 2: il supermercato, con un'altra IA"
    },
    {
      "file": "decks/esercizi-intelligenza-artificiale.html",
      "slide": 4,
      "title": "Esercizio 3: integrare i due inventari"
    }
  ],
  "decks/ia04-diversi-modelli-ia.html": [
    {
      "file": "decks/esercizi-intelligenza-artificiale.html",
      "slide": 5,
      "title": "Esercizio 4: riconoscere il modello giusto"
    }
  ],
  "decks/ms02-modellazione-base.html": [
    {
      "file": "decks/esercizi-modellazione-3d.html",
      "slide": 2,
      "title": "Mini-esercizio: il portachiavi"
    }
  ],
  "decks/ms03-esportazione-stampa-3d.html": [
    {
      "file": "decks/esercizi-modellazione-3d.html",
      "slide": 3,
      "title": "Una targhetta stampabile"
    }
  ],
  "decks/pr01-04-costrutti-verifica.html": [
    {
      "file": "decks/esercizi-programmare.html",
      "slide": 2,
      "title": "Esercizio: tre diagrammi da far girare"
    },
    {
      "file": "decks/esercizi-programmare.html",
      "slide": 3,
      "title": "Esercizio: tre diagrammi con un ciclo"
    }
  ],
  "decks/pr01-06-misure-calcoli-unita.html": [
    {
      "file": "decks/esercizi-programmare.html",
      "slide": 4,
      "title": "Laboratorio: salva una velocità senza ambiguità"
    },
    {
      "file": "decks/esercizi-programmare.html",
      "slide": 10,
      "title": "Verifica finale: che cosa manca?"
    }
  ],
  "decks/pr01-07-iterazione-cicli.html": [
    {
      "file": "decks/esercizi-programmare.html",
      "slide": 5,
      "title": "Verifica: progetta il ciclo"
    }
  ],
  "decks/pr02-02-questionario.html": [
    {
      "file": "decks/esercizi-programmare.html",
      "slide": 6,
      "title": "Collaudare il quiz"
    }
  ],
  "decks/pr04-01-strumenti-ambiente.html": [
    {
      "file": "decks/esercizi-programmare.html",
      "slide": 7,
      "title": "Esercizio: esplora senza installare tutto"
    }
  ],
  "decks/pr04-02-notepad-plus-plus.html": [
    {
      "file": "decks/esercizi-programmare.html",
      "slide": 8,
      "title": "Esercizio 6: pulisci un file di log"
    }
  ],
  "decks/pr04-03-sublime-text.html": [
    {
      "file": "decks/esercizi-programmare.html",
      "slide": 9,
      "title": "Esercizio 7: modifica una piccola codebase"
    }
  ],
  "decks/pr02-01-introduzione.html": [
    {
      "file": "decks/esercizi-programmare.html",
      "slide": 11,
      "title": "Progetto guidato: Abby e il Gatto"
    }
  ],
  "decks/pr04-05-git.html": [
    {
      "file": "decks/esercizi-programmare.html",
      "slide": 12,
      "title": "Laboratorio: una storia leggibile"
    }
  ],
  "decks/pr05-01-html-struttura.html": [
    {
      "file": "decks/esercizi-programmare.html",
      "slide": 13,
      "title": "Verifica: sai leggere il markup?"
    }
  ],
  "decks/pr05-02-html-link-immagini.html": [
    {
      "file": "decks/esercizi-programmare.html",
      "slide": 14,
      "title": "Verifica: colleghi e mostri?"
    }
  ],
  "decks/pr05-03-html-form-semantica.html": [
    {
      "file": "decks/esercizi-programmare.html",
      "slide": 15,
      "title": "Verifica: forma e significato"
    }
  ],
  "decks/pr05-04-css-stile-selettori.html": [
    {
      "file": "decks/esercizi-programmare.html",
      "slide": 16,
      "title": "Verifica: sai governare lo stile?"
    }
  ],
  "decks/rw02-01-email.html": [
    {
      "file": "decks/esercizi-reti-web.html",
      "slide": 2,
      "title": "Esercitazione pratica"
    },
    {
      "file": "decks/esercizi-reti-web.html",
      "slide": 3,
      "title": "Laboratorio pratico"
    }
  ],
  "decks/rw02-03-link-simbolici.html": [
    {
      "file": "decks/esercizi-reti-web.html",
      "slide": 4,
      "title": "Esercizio 3: costruisci un archivio senza duplicati"
    }
  ],
  "decks/rw02-06-accesso-remoto.html": [
    {
      "file": "decks/esercizi-reti-web.html",
      "slide": 5,
      "title": "Esercizio 4: collega due computer senza esporli a Internet"
    }
  ],
  "decks/rw01-06-internet-morto.html": [
    {
      "file": "decks/esercizi-reti-web.html",
      "slide": 6,
      "title": "Verifica finale: fatto, inferenza o teoria?"
    }
  ],
  "decks/sd06-piani-b-digitali.html": [
    {
      "file": "decks/esercizi-sicurezza.html",
      "slide": 2,
      "title": "Esercizio: mappa i tuoi punti unici"
    }
  ],
  "decks/sm09-benessere-digitale.html": [
    {
      "file": "decks/esercizi-smartphones.html",
      "slide": 2,
      "title": "Esercizio: Analizza il tempo sullo schermo"
    }
  ],
  "decks/su02-01-documenti.html": [
    {
      "file": "decks/esercizi-suite-ufficio.html",
      "slide": 2,
      "title": "Esercizio 1: prepara i contenuti dei documenti"
    }
  ],
  "decks/su02-02-word-scrivere-formattare.html": [
    {
      "file": "decks/esercizi-suite-ufficio.html",
      "slide": 3,
      "title": "Esercizio 2: formatta un listino modificabile"
    }
  ],
  "decks/su02-03-word-impaginare-revisionare.html": [
    {
      "file": "decks/esercizi-suite-ufficio.html",
      "slide": 4,
      "title": "Esercizio 3: revisiona un report di due pagine"
    }
  ],
  "decks/su02-04-word-documenti-professionali.html": [
    {
      "file": "decks/esercizi-suite-ufficio.html",
      "slide": 5,
      "title": "Esercizio 4: crea un kit professionale"
    }
  ],
  "decks/su03-03-fondamenti-matematici.html": [
    {
      "file": "decks/esercizi-suite-ufficio.html",
      "slide": 6,
      "title": "Esercizio 5: riconosci struttura e funzione"
    }
  ],
  "decks/su03-09-tabelle-pivot-avanzate.html": [
    {
      "file": "decks/esercizi-suite-ufficio.html",
      "slide": 7,
      "title": "Esercizio 6: costruisci un cruscotto vendite"
    },
    {
      "file": "decks/esercizi-suite-ufficio.html",
      "slide": 9,
      "title": "Esercizio 8: crea un cruscotto filtrabile"
    }
  ],
  "decks/su03-10-grafici.html": [
    {
      "file": "decks/esercizi-suite-ufficio.html",
      "slide": 8,
      "title": "Esercizio 7: scegli quattro grafici"
    },
    {
      "file": "decks/esercizi-suite-ufficio.html",
      "slide": 12,
      "title": "Revisione finale: ricostruire un grafico debole"
    }
  ],
  "decks/su03-16-collegamenti-fogli.html": [
    {
      "file": "decks/esercizi-suite-ufficio.html",
      "slide": 10,
      "title": "Esercizio 9: collega sorgente e report"
    }
  ],
  "decks/su03-17-oltre-il-foglio.html": [
    {
      "file": "decks/esercizi-suite-ufficio.html",
      "slide": 11,
      "title": "Esercizio 10: trasforma il foglio in specifica"
    }
  ],
  "decks/su03-14-vba.html": [
    {
      "file": "decks/esercizi-suite-ufficio.html",
      "slide": 13,
      "title": "Esercizio: Progetta la prima macro"
    },
    {
      "file": "decks/esercizi-suite-ufficio.html",
      "slide": 14,
      "title": "Esercizio: Attraversa tutti i fogli con For Each"
    },
    {
      "file": "decks/esercizi-suite-ufficio.html",
      "slide": 15,
      "title": "Esercizio: Prepara una macro da distribuire"
    }
  ],
  "decks/su03-15-google-apps-script.html": [
    {
      "file": "decks/esercizi-suite-ufficio.html",
      "slide": 16,
      "title": "Esercizio: Progetta un’automazione Workspace"
    },
    {
      "file": "decks/esercizi-suite-ufficio.html",
      "slide": 17,
      "title": "Esercizio: Progetta un invio di prova"
    },
    {
      "file": "decks/esercizi-suite-ufficio.html",
      "slide": 18,
      "title": "Esercizio: Prepara l’aggiornamento di un deployment"
    }
  ]
};
