/* Proprietà intellettuale di Francesco Antonio Binetti */
// Generated by scripts/build-exercise-index.js
// Do not edit by hand.
globalThis.EXERCISE_INDEX = {
  "cd01-01-licenze-oer.html": [
    {
      "file": "esercizi-contenuti-digitali.html",
      "slide": 2,
      "title": "Verifica: scegli e motiva"
    }
  ],
  "cd01-02-accessibilita-immagini.html": [
    {
      "file": "esercizi-contenuti-digitali.html",
      "slide": 3,
      "title": "Verifica: decorativa o informativa?"
    }
  ],
  "cd01-03-metadati-formati.html": [
    {
      "file": "esercizi-contenuti-digitali.html",
      "slide": 4,
      "title": "Verifica: archivio e logo"
    }
  ],
  "cd02-01-podcast-storytelling.html": [
    {
      "file": "esercizi-contenuti-digitali.html",
      "slide": 5,
      "title": "Verifica: racconta e consegna"
    }
  ],
  "ia02-esercizio-generazione.html": [
    {
      "file": "esercizi-intelligenza-artificiale.html",
      "slide": 2,
      "title": "Esercizio 1: l'inventario dell'ortofrutta"
    },
    {
      "file": "esercizi-intelligenza-artificiale.html",
      "slide": 3,
      "title": "Esercizio 2: il supermercato, con un'altra IA"
    },
    {
      "file": "esercizi-intelligenza-artificiale.html",
      "slide": 4,
      "title": "Esercizio 3: integrare i due inventari"
    }
  ],
  "ia04-diversi-modelli-ia.html": [
    {
      "file": "esercizi-intelligenza-artificiale.html",
      "slide": 5,
      "title": "Esercizio 4: riconoscere il modello giusto"
    }
  ],
  "ms02-modellazione-base.html": [
    {
      "file": "esercizi-modellazione-3d.html",
      "slide": 2,
      "title": "Mini-esercizio: il portachiavi"
    }
  ],
  "pr01-04-costrutti-verifica.html": [
    {
      "file": "esercizi-programmare.html",
      "slide": 2,
      "title": "Esercizio: tre diagrammi da far girare"
    },
    {
      "file": "esercizi-programmare.html",
      "slide": 3,
      "title": "Esercizio: tre diagrammi con un ciclo"
    }
  ],
  "pr01-06-misure-calcoli-unita.html": [
    {
      "file": "esercizi-programmare.html",
      "slide": 4,
      "title": "Laboratorio: salva una velocità senza ambiguità"
    }
  ],
  "pr01-07-iterazione-cicli.html": [
    {
      "file": "esercizi-programmare.html",
      "slide": 5,
      "title": "Verifica: progetta il ciclo"
    }
  ],
  "pr02-02-questionario.html": [
    {
      "file": "esercizi-programmare.html",
      "slide": 6,
      "title": "Collaudare il quiz"
    }
  ],
  "pr04-01-strumenti-ambiente.html": [
    {
      "file": "esercizi-programmare.html",
      "slide": 7,
      "title": "Esercizio: esplora senza installare tutto"
    }
  ],
  "pr04-02-notepad-plus-plus.html": [
    {
      "file": "esercizi-programmare.html",
      "slide": 8,
      "title": "Esercizio 6: pulisci un file di log"
    }
  ],
  "pr04-03-sublime-text.html": [
    {
      "file": "esercizi-programmare.html",
      "slide": 9,
      "title": "Esercizio 7: modifica una piccola codebase"
    }
  ],
  "rw02-01-email.html": [
    {
      "file": "esercizi-reti-web.html",
      "slide": 2,
      "title": "Esercitazione pratica"
    },
    {
      "file": "esercizi-reti-web.html",
      "slide": 3,
      "title": "Laboratorio pratico"
    }
  ],
  "rw02-03-link-simbolici.html": [
    {
      "file": "esercizi-reti-web.html",
      "slide": 4,
      "title": "Esercizio 3: costruisci un archivio senza duplicati"
    }
  ],
  "rw02-06-accesso-remoto.html": [
    {
      "file": "esercizi-reti-web.html",
      "slide": 5,
      "title": "Esercizio 4: collega due computer senza esporli a Internet"
    }
  ],
  "sd06-piani-b-digitali.html": [
    {
      "file": "esercizi-sicurezza.html",
      "slide": 2,
      "title": "Esercizio: mappa i tuoi punti unici"
    }
  ],
  "su02-01-documenti.html": [
    {
      "file": "esercizi-suite-ufficio.html",
      "slide": 2,
      "title": "Esercizio 1: prepara i contenuti dei documenti"
    }
  ],
  "su02-02-word-scrivere-formattare.html": [
    {
      "file": "esercizi-suite-ufficio.html",
      "slide": 3,
      "title": "Esercizio 2: formatta un listino modificabile"
    }
  ],
  "su02-03-word-impaginare-revisionare.html": [
    {
      "file": "esercizi-suite-ufficio.html",
      "slide": 4,
      "title": "Esercizio 3: revisiona un report di due pagine"
    }
  ],
  "su02-04-word-documenti-professionali.html": [
    {
      "file": "esercizi-suite-ufficio.html",
      "slide": 5,
      "title": "Esercizio 4: crea un kit professionale"
    }
  ],
  "su03-03-fondamenti-matematici.html": [
    {
      "file": "esercizi-suite-ufficio.html",
      "slide": 6,
      "title": "Esercizio 5: riconosci struttura e funzione"
    }
  ],
  "su03-09-tabelle-pivot-avanzate.html": [
    {
      "file": "esercizi-suite-ufficio.html",
      "slide": 7,
      "title": "Esercizio 6: costruisci un cruscotto vendite"
    },
    {
      "file": "esercizi-suite-ufficio.html",
      "slide": 9,
      "title": "Esercizio 8: crea un cruscotto filtrabile"
    }
  ],
  "su03-10-grafici.html": [
    {
      "file": "esercizi-suite-ufficio.html",
      "slide": 8,
      "title": "Esercizio 7: scegli quattro grafici"
    },
    {
      "file": "su03-10-grafici.html",
      "slide": 27,
      "title": "Revisione finale: ricostruire un grafico debole"
    }
  ],
  "su03-16-collegamenti-fogli.html": [
    {
      "file": "esercizi-suite-ufficio.html",
      "slide": 10,
      "title": "Esercizio 9: collega sorgente e report"
    }
  ],
  "su03-17-oltre-il-foglio.html": [
    {
      "file": "esercizi-suite-ufficio.html",
      "slide": 11,
      "title": "Esercizio 10: trasforma il foglio in specifica"
    }
  ],
  "sm09-benessere-digitale.html": [
    {
      "file": "sm09-benessere-digitale.html",
      "slide": 3,
      "title": "Tempo sullo schermo"
    }
  ],
  "su03-14-vba.html": [
    {
      "file": "su03-14-vba.html",
      "slide": 2,
      "title": "Introduzione a VBA"
    },
    {
      "file": "su03-14-vba.html",
      "slide": 12,
      "title": "For Each"
    },
    {
      "file": "su03-14-vba.html",
      "slide": 22,
      "title": "Sicurezza e distribuzione"
    }
  ],
  "su03-15-google-apps-script.html": [
    {
      "file": "su03-15-google-apps-script.html",
      "slide": 2,
      "title": "Che cos’è Apps Script"
    },
    {
      "file": "su03-15-google-apps-script.html",
      "slide": 13,
      "title": "GmailApp"
    },
    {
      "file": "su03-15-google-apps-script.html",
      "slide": 23,
      "title": "Deployment e versioni"
    }
  ],
  "pr02-01-introduzione.html": [
    {
      "file": "pr02-01-introduzione.html",
      "slide": 10,
      "title": "Progetto guidato: Abby e il Gatto"
    }
  ],
  "pr04-05-git.html": [
    {
      "file": "pr04-05-git.html",
      "slide": 18,
      "title": "Laboratorio: una storia leggibile"
    }
  ],
  "pr05-01-html-struttura.html": [
    {
      "file": "pr05-01-html-struttura.html",
      "slide": 11,
      "title": "Verifica: sai leggere il markup?"
    }
  ],
  "pr05-02-html-link-immagini.html": [
    {
      "file": "pr05-02-html-link-immagini.html",
      "slide": 9,
      "title": "Verifica: colleghi e mostri?"
    }
  ],
  "pr05-03-html-form-semantica.html": [
    {
      "file": "pr05-03-html-form-semantica.html",
      "slide": 9,
      "title": "Verifica: forma e significato"
    }
  ]
};
